<a href="https://colab.research.google.com/github/adgadiwan09/Week-1-python/blob/master/NUMPYbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#NUMPY BASICS

In [0]:
import numpy as np
import sys


In [7]:
print(np.__version__)

1.18.4


In [10]:
#creating array
np.array(1)

array(1)

In [0]:
#scalar 0 dimention array(1 value) 
#vector 1 dimention array(row/columns)
#matrix 2 dimention array(rows*column)

In [17]:
#scalar
a = np.array(2)
print(type(a))
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)

<class 'numpy.ndarray'>
2
1
()
0
int64


In [18]:
#vector
a = np.array([1,2,3,4,5])
print(type(a))
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)

<class 'numpy.ndarray'>
[1 2 3 4 5]
5
(5,)
1
int64


In [19]:
#matrix
a = np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(type(a))
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)

<class 'numpy.ndarray'>
[[1 2 3 4 5]
 [9 8 7 6 5]]
10
(2, 5)
2
int64


In [20]:
#3D array
a = np.array([[1,2,3,4,5],[9,8,7,6,5],[4,5,6,7,8]])
print(type(a))
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)


<class 'numpy.ndarray'>
[[1 2 3 4 5]
 [9 8 7 6 5]
 [4 5 6 7 8]]
15
(3, 5)
2
int64


In [26]:
#creating random vector 
r=np.random.randint(1,100,20)
r

array([65,  3, 55, 89, 13, 24, 89, 54,  3, 45, 10, 31,  6, 39, 11, 96, 88,
       63, 63, 79])

In [28]:
#conversion of vector into matrix
r.reshape(2,10)

array([[65,  3, 55, 89, 13, 24, 89, 54,  3, 45],
       [10, 31,  6, 39, 11, 96, 88, 63, 63, 79]])

In [29]:
#random float value
np.random.random(10)

array([0.86650575, 0.44536914, 0.64457297, 0.56005693, 0.9739357 ,
       0.0244755 , 0.17144375, 0.16097907, 0.88054913, 0.67470791])

In [31]:
#creating random matrix
r=np.random.randint(1,100,size=(5,2))
r

array([[22,  6],
       [61, 54],
       [54,  7],
       [23, 59],
       [40, 35]])

In [34]:
#printing range
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
#calculating distance
a=np.array([1,2])
b=np.array([3,4])
d1=np.linalg.norm(a)
d2=np.linalg.norm(b)
print(d1)
print(d2)
print(np.linalg.norm(a-b))

2.23606797749979
5.0
2.8284271247461903


In [39]:
#array of 1
f=np.ones(10,dtype=int)
f1=np.zeros([5,5])
f1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])